; PlatformIO Project Configuration
; Verstehbahnhof-Cache - Wemos D1 Mini Lite Firmware (ESP8285, 1 MB Flash)

[env:d1_mini_lite]
platform = espressif8266
board = d1_mini_lite
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dout
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
    bblanchon/ArduinoJson@^7.0.4
